//import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'RROSE66' at '11/6/19 1:54 PM' with Gradle 2.14.1
 *
 * @author RROSE66, @date 11/6/19 1:54 PM
 */
public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
//}
