/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'RROSE66' at '11/6/19 1:54 PM' with Gradle 2.14.1
 *
 * @author RROSE66, @date 11/6/19 1:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
